# The URL the site will be built for
base_url = "https://lukadeka.com"

title = "Luka Dekanozishvili"
description = "Welcome to my website! Here you'll find my tech blog, as well as my career path, projects, and hobbies."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default author for pages
author = "Luka Dekanozishvili"

# The taxonomies to be rendered for the site and their configuration of the default languages
# taxonomies = [
#   {name = "tags", feed = true, paginate_by = 20},
# ]

[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ðŸ˜„)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
# external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[markdown.highlighting]
theme = "github-dark"

# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

[extra]
long_title = "Luka Dekanozishvili"
favicon = "/images/author-image.webp"
